services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_db # Optional name for the container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: medsync!
      POSTGRES_DB: medsync_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "9000:5432"
  
volumes:
  medsync_db: