import app.api.v1.endpoints.auth
import app.api.v1.endpoints.notes
import app.api.v1.endpoints.reports
import app.api.v1.endpoints.users
import app.api.v1.endpoints.tests
import app.api.v1.endpoints.calibration
import app.api.v1.endpoints.umls
import app.api.v1.endpoints.report_instances
import app.api.v1.endpoints.report_templates